# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cooperator',
        ),
    ]
