# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userroles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('course_professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userroles.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user', to='userroles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, verbose_name='Название лаборатории')),
                ('lab_director', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userroles.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_user', to='userroles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=100, verbose_name='Название практики')),
                ('practice_responsible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userroles.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_user', to='userroles.UserProfile')),
            ],
        ),
    ]
