# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_distrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
