# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_distrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(choices=[('LAB', 'laboratory'), ('COURSE', 'course'), ('PRACTICE', 'practice'), ('SCIENCE_HEAD', 'science_director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('LAB', 'laboratory'), ('COURSE', 'course'), ('PRACTICE', 'practice'), ('SCIENCE_HEAD', 'science_director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'SENDED'), (1, 'ACCEPTED'), (2, 'DECLINED')], default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
