# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_distrib', '0002_auto_20170711_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
