# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_distrib', '0002_auto_20170711_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='request',
            name='change_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
