# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_distrib', '0003_auto_20170711_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(3)]),
        ),
    ]
