from django.conf.urls import url
from . import views

app_name = 'choose_distrib'
urlpatterns = [
    
    url(r'my_profile/(?P<user_id>[0-9]+)/student/practice', views.student_practice_form, name='student_practice'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/choice_course', views.student_course_form, name='student_choice_course'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/lab', views.student_lab, name='student_lab'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/sci_dir', views.student_sci_dir, name = 'student_sci_dir'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/practice/make_request', views.student_practice_make_request, name='student_practice_make_request'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/choice_course/make_request', views.student_choice_course_make_request, name='student_choice_course_make_request'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/lab/make_request', views.student_lab_make_request, name='student_lab_make_request'),
    url(r'my_profile/(?P<user_id>[0-9]+)/student/sci_dir/make_request', views.student_sci_dir_make_request, name = 'student_sci_dir_make_request'),
    url(r'my_profile/(?P<user_id>[0-9]+)/professor/practice', views.professor_practice_form, name='professor_practice'),
    url(r'my_profile/(?P<user_id>[0-9]+)/professor/choice_course', views.professor_choice_course_form, name='professor_choice_course'),
    url(r'my_profile/(?P<user_id>[0-9]+)/professor/lab', views.professor_lab, name='professor_lab'),
    url(r'my_profile/(?P<user_id>[0-9]+)/professor/sci_dir', views.professor_sci_dir, name = 'professor_sci_dir'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/practice/accept/(?P<user_id2>[0-9]+)', views.professor_practice_accept, name='professor_practice_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/choice_course/accept/(?P<user_id2>[0-9]+)', views.professor_practice_accept, name='professor_choice_course_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/lab/accept/(?P<user_id2>[0-9]+)', views.professor_practice_accept, name='professor_lab_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/sci_dir/accept/(?P<user_id2>[0-9]+)', views.professor_practice_accept, name = 'professor_sci_dir_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/practice/decline/(?P<user_id2>[0-9]+)', views.professor_practice_decline, name='professor_practice_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/choice_course/decline/(?P<user_id2>[0-9]+)', views.professor_practice_decline, name='professor_choice_course_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/lab/decline/(?P<user_id2>[0-9]+)', views.professor_practice_decline, name='professor_lab_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/professor/sci_dir/decline/(?P<user_id2>[0-9]+)', views.professor_practice_decline, name = 'professor_sci_dir_decline'),
    url(r'my_profile/(?P<user_id>[0-9]+)/sc_dir/practice', views.practice_form, name='sc_dir_practice'),
    url(r'my_profile/(?P<user_id>[0-9]+)/sc_dir/choice_course', views.course_form, name='sc_dir_choice_course'),
    url(r'my_profile/(?P<user_id>[0-9]+)/sc_dir/lab', views.lab, name='sc_dir_lab'),
    url(r'my_profile/(?P<user_id>[0-9]+)/sc_dir/sci_dir', views.sci_dir, name = 'sc_dir_sci_dir'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/practice/accept/(?P<user_id2>[0-9]+)', views.sc_dir_practice_accept, name='sc_dir_practice_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/choice_course/accept/(?P<user_id2>[0-9]+)', views.sc_dir_practice_accept, name='sc_dir_choice_course_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/lab/accept/(?P<user_id2>[0-9]+)', views.sc_dir_practice_accept, name='sc_dir_lab_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/sci_dir/accept/(?P<user_id2>[0-9]+)', views.sc_dir_practice_accept, name = 'sc_dir_sci_dir_accept'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/practice/decline/(?P<user_id2>[0-9]+)', views.sc_dir_practice_decline, name='sc_dir_practice_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/choice_course/decline/(?P<user_id2>[0-9]+)', views.sc_dir_practice_decline, name='sc_dir_choice_course_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/lab/decline/(?P<user_id2>[0-9]+)', views.sc_dir_practice_decline, name='sc_dir_lab_decline'),
    url(r'my_profile/(?P<user_id1>[0-9]+)/sc_dir/sci_dir/decline/(?P<user_id2>[0-9]+)', views.sc_dir_practice_decline, name = 'sc_dir_sci_dir_decline'),
    url(r'my_profile/(?P<user_id>[0-9]+)/cooperator/practice', views.practice_form, name='cooperator_practice'),
    url(r'my_profile/(?P<user_id>[0-9]+)/cooperator/choice_course', views.course_form, name='cooperator_choice_course'),
    url(r'my_profile/(?P<user_id>[0-9]+)/cooperator/lab', views.lab, name='cooperator_lab'),
    url(r'my_profile/(?P<user_id>[0-9]+)/cooperator/sci_dir', views.sci_dir, name = 'cooperator_sci_dir'),
  #  url(r'my_profile/(?P<user_id1>[0-9]+)/print', views.print_version, name = 'print'),
    
]